create table profiles (
  id uuid primary key references auth.users on delete cascade,
  username text,
  created_at timestamp with time zone default timezone('utc', now())
);

create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  content text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table profiles enable row level security;
alter table posts enable row level security;

create policy "Public profiles are viewable" 
  on profiles for select using (true);

create policy "Users can insert their own profile" 
  on profiles for insert with check (auth.uid() = id);

create policy "Anyone can read posts" 
  on posts for select using (true);

create policy "Authenticated users can insert posts" 
  on posts for insert with check (auth.uid() = user_id);
